export enum AttachmentExtension {
  applicationPdf = 'application/pdf',
  csv = 'csv',
  doc = 'doc',
  docx = 'docx',
  jpeg = 'jpeg',
  jpg = 'jpg',
  msg = 'msg',
  pdf = 'pdf',
  pjpeg = 'pjpeg',
  pjpg = 'pjpg',
  png = 'png',
  ppng = 'ppng',
  ppt = 'ppt',
  pptx = 'pptx',
  ptxt = 'ptxt',
  rtg = 'rtg',
  txt = 'txt',
  xls = 'xls',
  xlsx = 'xlsx',
  zip = 'zip',
  webp = 'webp',
}
